spring.application.name=KatamaranFilm
server.port=${PORT:8080}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.sql.init.mode=never
spring.thymeleaf.cache=false
server.servlet.session.tracking-modes=cookie

app.shared-password=${SHARED_PASSWORD}
tmdb.api.key=${TMDB_API_KEY}